server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

build:
  version: "v3"

accounts:
  message: "Message about Accounts"
  contactDetails:
    name: "John Doe"
    email: "jdoe@gmail.com"
  onCallSupport:
    - (123) 456-7890
    - (385) 987-4332